apiVersion: v1
kind: Service
metadata:
  name: user-service-headless
spec:
  clusterIP: None  # Headless service for StatefulSet
  selector:
    app.kubernetes.io/name: user-service
  ports:
    - name: http
      port: 3000
      targetPort: 3000